### ISSUE TITLE
Target Location Root - cannot be used

### ISSUE THREAD

**Issue by rdruss** [cescoffier/vertx-forge-addon#21]
While setting up a new project, the following dialogue pops up:

Use Target Location Root? (If specified, it won't create a subdirectory inside the specified Project location) [y/N]:

If you select "y" the project setup in Forge ends with the following error:

***ERROR*** Error while executing 'Vert.x: Setup'
***INFO*** (type "export VERBOSE=true" to enable stack traces)
***ERROR*** A project is required in the current context

**Comment by cescoffier** [comment]
@rdruss Can you tell me which version of forge and of the addon you are using.

I've tried:

```
[foo]$ project-new
***INFO*** Required inputs not satisfied, entering interactive mode
* Project name:  foo
? Top level package [org.foo]:
? Version [1.0.0-SNAPSHOT]:
? Final name:
? Project location [/Users/clement/tmp/foo]:
? Use Target Location Root? (If specified, it won't create a subdirectory inside the specified Project location) [y/N]: y
? Overwrite existing project location [y/N]: y

[0] (x) war
[1] ( ) vert.x
[2] ( ) jar
[3] ( ) parent
[4] ( ) forge-addon
[5] ( ) resource-jar
[6] ( ) ear
[7] ( ) from-archetype
[8] ( ) generic

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Project type: [0-8] 1

[0] (x) Maven
[1] ( ) None

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Build system: [0-1]
Configuring the vertx-maven-plugin...
maven-compiler-plugin already configured in the `pom.xml`, updating configuration...
vertx-maven-plugin is already configured in the `pom.xml` file - skipping its configuration
***SUCCESS*** Project named 'foo' has been created.
***SUCCESS*** Vert.x project created successfully
```

with the _master_ version, and latest forge release.

**Comment by rdruss** [comment]
I had just installed Forge 3.7.0 using homebrew on Mac.  Maybe the instructions were a little out of date.  I'll try to use the installation from the Forge repo.

**Comment by cescoffier** [comment]
I've updated the README yesterday. It was really (really) out of date.

**Comment by rdruss** [comment]
Tried testing to see if this is still an issue with the addon in the Forge repo.  Got stuck with https://github.com/forge/vertx-addon/issues/2

**Comment by rdruss** [comment]
Ok, still an issue with Forge 3.7.0 and vertx-forge-addon 1.2.3-SNAPSHOT

[with-forge]$ addon-list 
Currently installed addons:
**org.jboss.forge.addon:addon-manager,3.7.0.Final**
org.jboss.forge.addon:addon-manager-spi,3.7.0.Final
org.jboss.forge.addon:addons,3.7.0.Final
... <removed> ...
**org.jboss.forge.addon:vertx,1.2.3-SNAPSHOT**
org.jboss.forge.furnace.container:cdi,2.26.0.Final
org.jboss.forge.furnace.container:simple,2.26.0.Final
[with-forge]$ project-new
***INFO*** Required inputs not satisfied, entering interactive mode
* Project name:  faulty
? Top level package [org.faulty]:  io.vertx.book.message.faulty
? Version [1.0.0-SNAPSHOT]:  
? Final name:  Final
? Project location [/Users/rruss/workspace/with-forge]:  
? Use Target Location Root? (If specified, it won't create a subdirectory inside the specified Project location) [y/N]: y

[0] (x) war
[1] ( ) vert.x
[2] ( ) jar
[3] ( ) parent
[4] ( ) forge-addon
[5] ( ) resource-jar
[6] ( ) ear
[7] ( ) from-archetype
[8] ( ) generic

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Project type: [0-8] 1

[0] (x) Maven
[1] ( ) None

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Build system: [0-1] 0
***ERROR*** Error while executing 'Vert.x: Setup'
***INFO*** (type "export VERBOSE=true" to enable stack traces)
***ERROR*** A project is required in the current context

**Comment by rdruss** [comment]
with VERBOSE=true I get

***ERROR*** Error while executing 'Vert.x: Setup'
java.lang.IllegalStateException: A project is required in the current context
	at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:86)
	at io.vertx.forge.commands.SetupVertxCommand.execute(SetupVertxCommand.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.vertx.forge.commands.SetupVertxCommand_$$_javassist_a838648f-0152-40fe-9179-33c2ac984288.execute(SetupVertxCommand_$$_javassist_a838648f-0152-40fe-9179-33c2ac984288.java)
	at org.jboss.forge.addon.ui.result.navigation.CompositeCommand.execute(CompositeCommand.java:81)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
***ERROR*** A project is required in the current context

**Comment by rdruss** [comment]
Same error when using the command line option (not interactive mode):

```

project-new -named foo --build-system Maven --use-target-location-root --version 1.0.0-SNAPSHOT --top-level-package org.foo --type vert.x --named foo --dependencies vertx-infinispan --vertx-version 3.4.1   
***ERROR*** Error while executing 'Vert.x: Setup'
java.lang.IllegalStateException: A project is required in the current context
	at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:86)
	at io.vertx.forge.commands.SetupVertxCommand.execute(SetupVertxCommand.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.vertx.forge.commands.SetupVertxCommand_$$_javassist_a838648f-0152-40fe-9179-33c2ac984288.execute(SetupVertxCommand_$$_javassist_a838648f-0152-40fe-9179-33c2ac984288.java)
	at org.jboss.forge.addon.ui.result.navigation.CompositeCommand.execute(CompositeCommand.java:81)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
***ERROR*** A project is required in the current context

```

**Comment by cescoffier** [comment]
I was able to reproduce it, but I don't know how to fix it. the project is not yet created, so the command should not be executed (as they all require an existing project). @gastaldi can you tell me how to create the project programmatically? I have the project builder, but how do we pass it all the parameters?

**Comment by gastaldi** [comment]
@cescoffier that's weird, the project should have been created in the NewProjectWizardImpl class (using ProjectFactory). Let me investigate what's going on

**Comment by gastaldi** [comment]
@cescoffier @rdruss it's a bug in Forge. I created https://issues.jboss.org/browse/FORGE-2753 and will be fixed in 3.7.1.Final
